### ISSUE TITLE
read multiple values from stdin?

### ISSUE THREAD

**Issue by jonase** [prepor/ocaml-edn#3]
Hi!  Thanks for creating ocaml-edn! 

This is more a question than a bug report, which I hope is ok. I'm trying to read multiple values from stdin but I seem to be doing something wrong. I'm basically trying to replicate the following clojure code:

``` clojure
(ns rdr.core)

(defn -main []
  (try
    (while true
      (prn (read)))
    (catch Exception e)))
```

which works as follows.

```
$ echo '{:foo "bar"} [1 2 3]' | lein run -m rdr.core
{:foo "bar"}
[1 2 3]
```

In OCaml I'm trying to do the following:

``` ocaml
let rec loop () =
  try
    print_endline (Edn.to_string (Edn.from_channel stdin));
    loop ()
  with
    End_of_file -> ()

let _ = loop ()
```

which results in

```
$ ocamlbuild -use-ocamlfind -pkg=edn rdr.native
$ echo '{:foo "bar"} [1 2 3]' | ./rdr.native
{:foo "bar" }
```

so it seems like `End_of_file` is reached after the first value is read? @prepor @Leonidas-from-XIV Any help on this would be much appreciated.

**Comment by Leonidas-from-XIV** [comment]
@jonase That's not quite accurate, when you start it in the shell and enter the forms separated by newline, the code you run is just fine.

The reason why it terminates is, that you feed in a form which is `{:foo "bar"} [1 2 3]` at once, which is not not EDN, but it _starts_ with EDN, so the parser parses that and returns you the form, dropping the rest of the bytes in the `lexbuf`.

To confirm my suspicion, here's an adapted version of your program, that parses 2 forms:

``` ocaml
let rec loop () =
  let lexbuf = Lexing.from_channel stdin in
  try
    let parsed = Edn.parse lexbuf in
    print_endline @@ Edn.to_string parsed;
    print_endline @@ string_of_int @@ lexbuf.Lexing.lex_curr_p.Lexing.pos_cnum;
    let parsed2 = Edn.parse lexbuf in
    print_endline @@ Edn.to_string parsed2;
    loop ()
  with
    End_of_file -> ()

let () =
  loop ()
```

(I've taken the liberty to expose `Edn.parse` in ocaml-edn for demonstration purposes)

What you see here is that the position of the cursor in the lexing buffer after parsing is at 12, i.e. exactly after the end of the first form, because the parser finished with the form here, so restarting the parser from that position parsed the second form (`[1 2 3]`).

Hope that helps!

**Comment by jonase** [comment]
@Leonidas-from-XIV Thanks. This helps a lot!

> when you start it in the shell and enter the forms separated by newline, the code you run is just fine

I noticed this too, and was confused by it

I was looking at what other libraries do, and found Yojson's [stream_from_channel](https://github.com/mjambon/yojson/blob/master/read.mli#L81-L93) and [this comment](https://github.com/mjambon/yojson/issues/16#issuecomment-137814357). Perhaps this abstraction could be added to `ocaml-edn` as well @prepor? If I understand it correctly it would suit my use case very nicely. 

I can work on a PR later this week.

**Comment by Leonidas-from-XIV** [comment]
Implementing `stream_from_channel` sounds like the best way to go about it, I agree.

**Comment by prepor** [comment]
Hello! Good to know that my code is useful for someone else ;)

EDN is fully compatible for multiple values by edn-spec, so we should provide it in good implementation.

I also want to warn, that there are some lacks in this implementation, e.g. there is no support of comments at the moment.

I hope I'll have time at weekend to implement something like `stream_from_channel` (but not sure that `Stream` abstraction is good with async-io) and fix at least the lacking of comments support.

**Comment by prepor** [comment]
Comments are supported now ;)
